scenicSpots = ['Grand Canyon National Park', 'Prague', 'Serengeti National Park', 'Giants Causeway', 'Machu Picchu']
print(scenicSpots)
print(sorted(scenicSpots))
print(scenicSpots)
print(sorted(scenicSpots, reverse=True))
print(scenicSpots)
scenicSpots.reverse()
print(scenicSpots)
scenicSpots.reverse()
print(scenicSpots)
scenicSpots.sort()
print(scenicSpots)
scenicSpots.sort(reverse=True)
print(scenicSpots)